resources:
- name: p-thing-source-ci
  type: git
  source:
    uri: https://github.com/mcarlson-sb/concourse-experiment.git
    branch: p-thing-ci

jobs:
- name: test-p-thing
  build-logs-to-retain: 5
  plan:
  - timeout: 1m
    do:
    - get: p-thing-source-ci
      trigger: true
    - task: test-p-thing
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: echo
          args: ["I have tested the p-thing, world!"]
